# Introduction to Tensorflow

## Notes from video:

## Notes from TF Introduction:

In [2]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\macik\\anaconda3\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [4]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.566999912261963>


In [8]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

The rank of a tensor is direclty related to the deepest level of nested lists

In [9]:
rank2_tensor.shape

TensorShape([2, 2])

In [10]:
tensor1 = tf.ones([1, 2, 3])
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place.

The number of elements in the reshaped tensor MUST match the number in the original.

In [11]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [12]:
# 2D TENSOR:
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [16]:
# Now let's slice, chef
three = tensor[0, 2]
print(three)

row1 = tensor[0]
print(row1)

column1 = tensor[:, 0]
print(column1)

row_2_and_4 = tensor[1::2] # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


Most common kinds of tensors:  
- Variable  
- Constant  
- Placeholder  
- SparseTensor  

Everything is immutable besides Variable

# Tensorflow Questions:

## Question 1: 
Create a scalar tensor with a value of 5 (integer)  
Create a scalar with a value of 5.0 (float) and check its dtype and dimension

In [25]:
scaly = tf.constant(5)
floaty = tf.constant(5.0)

print(scaly)
print("floaty dtype: " + f'{floaty.dtype}')
print('floaty dimension: ' + f'{floaty.ndim}')

tf.Tensor(5, shape=(), dtype=int32)
floaty dtype: <dtype: 'float32'>
floaty dimension: 0


In [28]:
vector = tf.constant([10., 15., 20.])

print(vector)
print('number of dimensions of the vector: ' + f'{vector.ndim}')

tf.Tensor([10. 15. 20.], shape=(3,), dtype=float32)
number of dimensions of the vector: 1


## Question 2:

In [29]:
vector = tf.constant([1, 2, 3, 4, 5])
print(vector)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [30]:
matrix = tf.constant([
    [1,2],
    [3,4]
])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
2


## Question 3:

In [32]:
# 3x3 Matrix:
matrix_three = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix_three)

matrix_two = tf.constant([[1, 2], [3, 4], [5, 6]])
print(matrix_two)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [33]:
tensor = tf.constant([
    [[1,2]],
    [[3,4]]
])
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[1 2]]

 [[3 4]]], shape=(2, 1, 2), dtype=int32)
3


## Question 4:

In [35]:
tensor = tf.constant([[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]])
print(tensor)

tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]], shape=(3, 1, 3), dtype=int32)


In [36]:
# Everything is the same except you use tf.Variable instead of tf.Constant

var_tensor = tf.Variable([
    [[1,2,3]],
    [[4,5,6]],
    [[7,8,9]]
])


print(var_tensor)

<tf.Variable 'Variable:0' shape=(3, 1, 3) dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])>


In [37]:
tf.zeros(shape=(2,2),dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

## Question 5:

In [39]:
tf.zeros(shape=(4, 3), dtype='float16')

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)>

In [40]:
# Create the tensor variable object
tensor = tf.Variable(tf.zeros(shape=(4,3),dtype=tf.int32))

tensor

<tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [41]:
tensor[1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [42]:
# Notice here we are assinging the second row of the matrix
tensor[1].assign([2,2,2])

tensor

<tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
array([[0, 0, 0],
       [2, 2, 2],
       [0, 0, 0],
       [0, 0, 0]])>

## Question 6: